export type OnboardingContextType = {
    fullName: string;
    setFullName: (name: string) => void;
    username: string;
    setUsername: (username: string) => void;
    photoUri: string | null;
    setPhotoUri: (uri: string | null) => void;
    progressPhotos: string[];
    setProgressPhotos: (photos: string[]) => void;
    deleteProgressPhoto: (index: number) => void;
    usernameTaken: boolean;
    isUsernameLoading: boolean;
    suggestions: string[];
    currentWeight: number;
    setCurrentWeight: (weight: number) => void;
    targetWeight: number;
    setTargetWeight: (weight: number) => void;
    weightUnit: 'KG' | 'LB';
    setWeightUnit: (unit: 'KG' | 'LB') => void;
    toggleWeightUnit: (unit: 'KG' | 'LB') => void;
    activityLevel: number;
    setActivityLevel: (level: number) => void;
    dailyCalories: number;
    setDailyCalories: (calories: number) => void;
    goalDate: string | null;
    setGoalDate: (date: string | null) => boolean;
    currentIndex: number;
    totalSteps: number;
    handleContinue: () => void;
    handleBack: () => void;
    handleFinish: () => void;
};