export const computeHealthRating = (food: {
  calories_per_100g: number;
  protein_per_100g: number;
  fat_per_100g: number;
  carbs_per_100g: number;
  category?: string;
  source?: string;
}): number => {
  const cal = food.calories_per_100g || 0;
  const protein = food.protein_per_100g || 0;
  const fat = food.fat_per_100g || 0;
  const carbs = food.carbs_per_100g || 0;
  const category = (food.category || "").toLowerCase();
  const source = (food.source || "").toLowerCase();
  if (cal === 0 && protein === 0 && fat === 0 && carbs === 0) return 5.0;
  let score = 5.0;
  if (cal <= 30) score += 2.0;
  else if (cal <= 60) score += 1.5;
  else if (cal <= 100) score += 1.0;
  else if (cal <= 150) score += 0.5;
  else if (cal <= 250) score += 0.0;
  else if (cal <= 400) score -= 1.0;
  else if (cal <= 500) score -= 2.0;
  else score -= 3.0;
  if (protein >= 20) score += 1.5;
  else if (protein >= 10) score += 1.0;
  else if (protein >= 5) score += 0.5;
  if (fat >= 30) score -= 2.0;
  else if (fat >= 20) score -= 1.0;
  else if (fat >= 10) score -= 0.5;
  if (carbs >= 60) score -= 1.0;
  else if (carbs >= 40) score -= 0.5;
  if (category === "fruits") score += 1.5;
  else if (category === "vegetables") score += 2.0;
  if (source === "openfoodfacts") score -= 0.5;
  return Math.min(10, Math.max(0, Math.round(score * 10) / 10));
};